language: node_js
node_js:
- node
deploy:
  provider: npm
  email: 915854513@qq.com
  skip_cleanup: true
  api_key:
    secure: WGn+fgE4p/Zgwown/D1aimocXs98xDnpHvlKa8naq9jt8U2MCqC+V0/x0SiBAJCJvDHEDTMqa1rQsCp7/1pzUcX3UV8scYufluQ2Uk69wxiYIVa9qREWpzYp/Iamqgy3F9e3bNrCHZRs40v4IlLDqYiH/EmUFdcj9s4G+bxDqY4yerU6G1dMMQ8lgzGVRRkEo/InND39eqDOUbHv2KlSDTgJ/nSzdGFF7ZCUnW0ZcSwTFjytk70TRDC9m3DZKzJTnz8FnxB0Rkfdz1k3NSGHSrIZWFZh2rNykkcM/gX5lLvhJu3ZJlQBVn8psVZubXgzAXyvh40T+WU8v0CdGhL184yqWNZmJdvWRzTDqrgpSag54XUq3l+fPZPdTft49K79DG2GeMDAMom/pO3fhVW8jodwB72iN2NU4HN0B6VBLUQEcsd3EZW5skhaS4hm6f+TWA7JZ/5G+4ZMgYeIIG1tp0bAnuWwHIi9eN/f96qJ2U4Yiac5gq1AZ2jFpSGhyE+HMeiosEpPMDzTMyrXrW7CMRa5PfyPG5GEOLyqUoLN5QhJzwDBXK+j6l+hZaHcPAfqku71tBucT57+lhvLnE9yT2b43NK0GgvRCrqIR2MnmjYdeowXhpRUnW3wT/OnjKVfLA7jjjokIdNgirN+UFnF7s37YkrzfNeqvFfWyYeHc00=
  on:
    tags: true